### ISSUE TITLE
Throne of the Tides not detected

### ISSUE THREAD

**Issue by jonathanfernandezfm** [keysc3/MplusGains#17]
**Describe the bug**
Throne of the Tides allows me to select from +2 and ahead although I have done a +17 (depleted)

**To Reproduce**
1. Open /mpg 
2. Throne of the Tides shows me the whole range

**Expected behavior**
Let me select only from keys that upgrade

**Screenshots**
![image](https://github.com/keysc3/MplusGains/assets/33097447/9faf18ce-082f-4cb5-a29a-a67e1beefa67)

**Additional context**
None

**Comment by keysc3** [comment]
Thanks for the report. Are there any Lua errors with the addon? Did this happen after completing a key?

**Comment by keysc3** [comment]
After looking at your 17 Throne of the Tides run, the key selection scroll frame for that dungeon is actually correct. Your run was overtime by more than 40% of the dungeon timer so that run doesn't actually reward you any score, so any key can still grant you score. I never checked the edge case for when a players best run is worth 0 score so I'd guess that is why a 17 shows up in your best runs frame. I'll check for this case and replace the runs number with a dash to avoid any confusion.

**Comment by jonathanfernandezfm** [comment]
Thank you so much for the quick response and conclusion. I did not even consider that case because I was not fully aware it was giving me no score.

**Comment by jonathanfernandezfm** [comment]
Now that I check too. I am getting points from a previous run that was timed. So instead of considering 0 points given by the "best", it should consider the previous valid and max score given run. It seems the "best" run is not the higher scorer one 😁

**Comment by keysc3** [comment]
What you are suggesting isn't necessary. Both of the alternating affixes (Tyrannical and Fortified) have a "best" run that contributes to a dungeons total score. In this case the highest scoring Tyrannical key is contributing 0 score and the highest scoring Fortified key is contributing some other amount.

**Comment by keysc3** [comment]
The "best" run is the highest scoring so technically there is no need to replace a "best" runs level with a "-" as I did because that is the key contributing to the dungeons total score. However I think making that replacement will cause less confusion among users.
